/*
Copyright (c) 2024 Americus Maximus

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#include "Input.hxx"
#include "State.hxx"

INPUTSTATEMODULECONTAINER InputState;

STATIC DIOBJECTDATAFORMAT InputDetails[MAX_INPUT_STATE_COUNT] =
{
    { &GUID_Key, 0, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(0) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 1, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(1) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 2, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(2) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 3, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(3) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 4, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(4) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 5, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(5) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 6, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(6) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 7, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(7) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 8, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(8) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 9, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(9) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 10, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(10) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 11, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(11) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 12, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(12) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 13, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(13) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 14, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(14) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 15, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(15) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 16, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(16) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 17, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(17) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 18, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(18) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 19, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(19) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 20, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(20) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 21, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(21) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 22, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(22) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 23, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(23) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 24, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(24) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 25, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(25) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 26, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(26) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 27, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(27) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 28, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(28) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 29, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(29) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 30, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(30) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 31, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(31) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 32, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(32) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 33, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(33) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 34, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(34) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 35, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(35) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 36, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(36) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 37, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(37) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 38, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(38) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 39, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(39) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 40, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(40) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 41, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(41) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 42, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(42) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 43, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(43) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 44, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(44) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 45, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(45) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 46, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(46) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 47, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(47) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 48, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(48) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 49, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(49) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 50, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(50) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 51, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(51) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 52, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(52) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 53, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(53) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 54, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(54) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 55, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(55) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 56, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(56) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 57, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(57) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 58, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(58) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 59, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(59) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 60, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(60) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 61, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(61) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 62, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(62) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 63, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(63) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 64, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(64) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 65, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(65) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 66, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(66) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 67, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(67) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 68, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(68) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 69, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(69) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 70, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(70) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 71, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(71) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 72, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(72) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 73, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(73) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 74, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(74) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 75, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(75) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 76, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(76) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 77, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(77) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 78, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(78) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 79, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(79) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 80, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(80) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 81, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(81) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 82, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(82) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 83, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(83) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 84, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(84) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 85, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(85) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 86, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(86) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 87, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(87) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 88, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(88) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 89, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(89) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 90, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(90) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 91, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(91) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 92, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(92) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 93, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(93) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 94, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(94) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 95, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(95) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 96, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(96) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 97, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(97) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 98, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(98) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 99, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(99) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 100, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(100) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 101, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(101) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 102, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(102) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 103, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(103) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 104, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(104) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 105, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(105) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 106, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(106) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 107, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(107) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 108, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(108) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 109, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(109) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 110, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(110) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 111, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(111) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 112, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(112) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 113, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(113) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 114, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(114) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 115, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(115) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 116, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(116) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 117, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(117) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 118, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(118) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 119, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(119) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 120, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(120) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 121, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(121) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 122, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(122) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 123, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(123) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 124, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(124) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 125, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(125) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 126, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(126) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 127, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(127) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 128, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(128) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 129, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(129) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 130, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(130) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 131, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(131) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 132, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(132) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 133, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(133) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 134, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(134) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 135, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(135) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 136, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(136) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 137, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(137) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 138, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(138) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 139, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(139) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 140, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(140) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 141, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(141) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 142, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(142) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 143, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(143) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 144, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(144) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 145, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(145) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 146, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(146) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 147, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(147) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 148, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(148) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 149, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(149) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 150, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(150) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 151, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(151) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 152, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(152) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 153, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(153) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 154, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(154) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 155, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(155) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 156, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(156) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 157, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(157) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 158, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(158) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 159, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(159) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 160, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(160) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 161, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(161) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 162, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(162) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 163, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(163) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 164, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(164) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 165, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(165) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 166, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(166) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 167, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(167) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 168, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(168) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 169, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(169) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 170, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(170) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 171, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(171) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 172, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(172) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 173, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(173) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 174, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(174) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 175, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(175) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 176, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(176) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 177, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(177) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 178, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(178) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 179, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(179) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 180, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(180) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 181, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(181) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 182, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(182) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 183, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(183) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 184, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(184) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 185, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(185) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 186, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(186) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 187, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(187) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 188, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(188) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 189, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(189) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 190, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(190) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 191, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(191) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 192, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(192) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 193, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(193) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 194, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(194) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 195, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(195) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 196, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(196) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 197, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(197) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 198, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(198) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 199, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(199) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 200, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(200) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 201, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(201) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 202, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(202) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 203, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(203) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 204, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(204) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 205, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(205) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 206, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(206) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 207, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(207) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 208, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(208) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 209, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(209) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 210, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(210) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 211, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(211) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 212, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(212) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 213, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(213) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 214, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(214) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 215, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(215) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 216, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(216) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 217, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(217) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 218, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(218) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 219, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(219) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 220, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(220) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 221, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(221) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 222, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(222) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 223, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(223) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 224, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(224) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 225, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(225) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 226, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(226) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 227, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(227) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 228, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(228) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 229, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(229) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 230, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(230) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 231, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(231) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 232, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(232) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 233, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(233) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 234, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(234) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 235, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(235) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 236, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(236) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 237, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(237) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 238, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(238) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 239, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(239) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 240, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(240) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 241, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(241) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 242, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(242) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 243, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(243) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 244, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(244) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 245, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(245) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 246, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(246) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 247, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(247) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 248, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(248) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 249, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(249) | DIDFT_BUTTON, DIDOI_NONE },

    { &GUID_Key, 250, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(250) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 251, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(251) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 252, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(252) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 253, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(253) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 254, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(254) | DIDFT_BUTTON, DIDOI_NONE },
    { &GUID_Key, 255, DIDFT_OPTIONAL | DIDFT_MAKEINSTANCE(255) | DIDFT_BUTTON, DIDOI_NONE }
};

// 0x10023850
BOOL InitializeDirectInputAction(VOID)
{
    if (DirectInputCreateA(State.Window->Instance, DIRECTINPUT_VERSION, &InputState.Instance, NULL) != DI_OK) { return FALSE; }

    if (InputState.Instance->CreateDevice(GUID_SysKeyboard, &InputState.Device, NULL) != DI_OK) { return FALSE; }

    {
        // 0x1003c014   
        DIDATAFORMAT format;
        ZeroMemory(&format, sizeof(DIDATAFORMAT));

        format.dwSize = sizeof(DIDATAFORMAT);
        format.dwObjSize = sizeof(DIOBJECTDATAFORMAT);
        format.dwFlags = DIDF_RELAXIS;
        format.dwDataSize = MAX_INPUT_STATE_COUNT * sizeof(U8);
        format.dwNumObjs = MAX_INPUT_STATE_COUNT;
        format.rgodf = InputDetails;

        if (InputState.Device->SetDataFormat(&format) != DI_OK) { return FALSE; }
    }

    if (InputState.Device->SetCooperativeLevel(State.Window->HWND, DISCL_FOREGROUND | DISCL_NONEXCLUSIVE) != DI_OK) { return FALSE; }

    InputState.Device->Acquire();

    return TRUE;
}

// 0x10023920
BOOL AcquireDirectInputAction(VOID)
{
    HRESULT result = InputState.Device->GetDeviceState(MAX_INPUT_STATE_COUNT * sizeof(U8), InputState.State);

    while (result == DIERR_NOTACQUIRED || result == DIERR_INPUTLOST)
    {
        result = InputState.Device->Acquire();

        if (result != DI_OK) { ZeroMemory(InputState.State, MAX_INPUT_STATE_COUNT * sizeof(U8));  return TRUE; }

        result = InputState.Device->GetDeviceState(MAX_INPUT_STATE_COUNT * sizeof(U8), InputState.State);
    }

    if (result != DI_OK) { ZeroMemory(InputState.State, MAX_INPUT_STATE_COUNT * sizeof(U8));  return TRUE; }

    return TRUE;
}

// 0x10023970
BOOL ReleaseDirectInputAction(VOID)
{
    if (InputState.Device != NULL)
    {
        InputState.Device->Unacquire();
        DIRECTINPUTRELEASE(InputState.Device);
    }

    DIRECTINPUTRELEASE(InputState.Instance);

    return TRUE;
}

// 0x100239c0
BOOL InputMessageAction(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp, LRESULT* result)
{
    return TRUE;
}